EcomaintSite/EcomaintSite/Controllers/DashboardController.cs
using Microsoft.AspNet.Identity;
using Model.Interface;
using System;
using System.Linq;
using System.Web.Mvc;

namespace EcomaintSite.Controllers
{
    public class DashboardController : Controller
    {
        IUserRepository user;
        IChartRepository chart;
        public DashboardController(IUserRepository _user, IChartRepository _chart)
        {
            user = _user;
            chart = _chart;
        }
        [Authorize]
        public ActionResult Index()
        {
            var us = user.GetUserByID(User.Identity.GetUserName());
            ViewBag.TenNguoiDung = us.FullName;
            ViewBag.Username = User.Identity.GetUserName();
            ViewBag.PhongBan = user.GetPhongBan(Convert.ToInt32(us.DepartmentID));
            ViewBag.SoMay = chart.GetSoMay().ToString();
            return View();
        }

        public JsonResult GetDeviceInfo() =>
            Json(new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(chart.GetDeviceInfo(SessionVariable.TypeLanguage).ToList()).Replace("y\":\"", "y\":").Replace("\",\"color\":", ",\"color\":"), JsonRequestBehavior.AllowGet);
     
        public JsonResult GetDeviceStatus() =>
             Json(new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(chart.GetDeviceStatus(DateTime.Now, User.Identity.GetUserName(), SessionVariable.TypeLanguage).ToList()).Replace("y\":\"", "y\":").Replace("\",\"color\":", ",\"color\":"), JsonRequestBehavior.AllowGet);
     
        public JsonResult GetSituationWO() => 
            Json(new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(chart.GetSituationWO(SessionVariable.TypeLanguage).ToList()).Replace("\"[", "[").Replace("]\"", "]"), JsonRequestBehavior.AllowGet);
    
        public JsonResult GetSituationWOColumn() =>
            Json(new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(chart.GetSituationWOColumn(SessionVariable.TypeLanguage).ToList()).Replace("\"[", "[").Replace("]\"", "]"), JsonRequestBehavior.AllowGet);

    }
}

EcomaintSite/EcomaintSite/Controllers/MyEcomainController.cs
//using Dynamsoft.Barcode;
using Microsoft.AspNet.Identity;
using Model.Combobox;
using Model.Interface;
using Model.Interface.IRepository;
using Model.Repository.Repository;
//using Newtonsoft.Json;
//using Newtonsoft.Json.Linq;
using System;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//using ZXing;
using System.Text;
using QRCodeDecoderLibrary;
using ZXing;
using System.Drawing;
using System.ComponentModel;
//using IronBarCode;

namespace EcomaintSite.Controllers
{
    public class MyEcomainController : Controller
    {

        private ICombobox _Combobox;
        private IMyEcomainRepository _MyEcomainRepository;
        private ICombobox Combobox()
        {
            return _Combobox ?? (_Combobox = new Combobox());
        }

        private IMyEcomainRepository MyEcomain()
        {
            return _MyEcomainRepository ?? (_MyEcomainRepository = new MyEcomainRepository());
        }
        // GET: MyEcomain
        [Authorize]
        public ActionResult Index()
        {
            var us = User.Identity.GetUserName();
            Loadcombo(us);
            return View();
        }
        private void Loadcombo(string user)
        {
            ViewBag.NhaXuong = Combobox().GetCbbDiaDiem(user, SessionVariable.TypeLanguage, 1);
            //ViewBag.HeThong = Combobox().GetCbbHeThong(user, SessionVariable.TypeLanguage, 1);
            //ViewBag.LoaiMay = Combobox().GetCbbLoaiMay(user, SessionVariable.TypeLanguage, 1);
            //ViewBag.May = Combobox().GetCbbMay(user, SessionVariable.TypeLanguage, 1);
            //ViewBag.LoaiCV = Combobox().GetCbbLoaiCV(user, SessionVariable.TypeLanguage, 1);
        }
        [Authorize]
        public JsonResult GetPhieuBaoTri(string ms_nx, string ms_ht, string ms_loaimay, string ms_may)
        {
            var lst = MyEcomain().GetPhieuBaoTris(User.Identity.GetUserName(), SessionVariable.TypeLanguage, ms_nx, Convert.ToInt32(ms_ht), ms_loaimay, ms_may).Select(x => new
            {
                MS_PHIEU_BAO_TRI = x.MS_PHIEU_BAO_TRI,
                MS_MAY = x.MS_MAY,
                TEN_MAY = x.TEN_MAY,
                TEN_LOAI_BT = x.TEN_LOAI_BT,
                TEN_TINH_TRANG = x.TEN_TINH_TRANG,
                NGAY_BD_KH = x.NGAY_BD_KH.ToString("dd/MM/yyyy"),
                NGAY_KT_KH = x.NGAY_KT_KH.ToString("dd/MM/yyyy"),
                Ten_N_XUONG = x.Ten_N_XUONG
            });
            return Json(lst, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetGiamSatTinhTrang(string fromDate, string toDate, string ms_nx, string ms_ht, string ms_loaimay, string ms_may, string ms_loaicv)
        {
            var lst = MyEcomain().GetGSTRs(User.Identity.GetUserName(), SessionVariable.TypeLanguage, Convert.ToDateTime(fromDate, new CultureInfo("vi-vn")).ToString("yyyy/MM/dd"), Convert.ToDateTime(toDate, new CultureInfo("vi-vn")).ToString("yyyy/MM/dd"), ms_nx, Convert.ToInt32(ms_ht), ms_loaimay, ms_may, Convert.ToInt32(ms_loaicv)).Select(x => new
            {
                MS_MAY = x.MS_MAY,
                TEN_MAY = x.TEN_MAY,
                TEN_BO_PHAN = x.TEN_BO_PHAN,
                TEN_TS_GSTT = x.TEN_TS_GSTT,
                CHU_KY_DO = x.CHU_KY_DO,
                NGAY_KT_CUOI = x.NGAY_KT_CUOI.ToString("dd/MM/yyyy"),
                TEN_GIA_TRI = x.TEN_GIA_TRI,
                NGAY_KT_KE = x.NGAY_KT_KE.ToString("dd/MM/yyyy"),
                CAC_THUC_HIEN = x.CAC_THUC_HIEN,
                THOI_GIAN = x.THOI_GIAN
            });
            return Json(lst, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GeMyecomain(string fromDate, string toDate, string ms_nx, string may, string giadoan)
        {
            try
            {
                var lst = MyEcomain().GetMyEcomain(User.Identity.GetUserName(), SessionVariable.TypeLanguage, Convert.ToDateTime(fromDate, new CultureInfo("vi-vn")).ToString("yyyy/MM/dd"), Convert.ToDateTime(toDate, new CultureInfo("vi-vn")).ToString("yyyy/MM/dd"), ms_nx, may, Convert.ToInt32(giadoan)).Select(x => new
                {
                    MS_MAY = x.MS_MAY,
                    TEN_MAY = x.TEN_MAY,
                    PBT = x.PBT,
                    GSTT = x.GSTT
                });
                return Json(lst, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json("error", JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult ShowPBT(string id)
        {
            string nx = Request["nhaxuong"];
            string tngay = Request["fromday"];
            string dengnay = Request["today"];
            return RedirectToAction("show", "WorkOrder", new { msnx = nx, msmay = id, todate = tngay, fromdate = dengnay });
        }
        public ActionResult ShowGSTT(string id)
        {
            string nx = Request["nhaxuong"];
            string tungay = Request["fromday"];
            string dengnay = Request["today"];
            return RedirectToAction("Show", "Monitoring", new { msnx = nx, msmay = id, tngay = tungay, dngay = dengnay });
        }

        private static string QRCodeResult
        (
        byte[][] DataByteArray
        )
        {
            // no QR code
            if (DataByteArray == null) return string.Empty;

            // image has one QR code
            if (DataByteArray.Length == 1) return ForDisplay(QRDecoder.ByteArrayToStr(DataByteArray[0]));

            // image has more than one QR code
            StringBuilder Str = new StringBuilder();
            for (int Index = 0; Index < DataByteArray.Length; Index++)
            {
                if (Index != 0) Str.Append("\r\n");
                Str.AppendFormat("QR Code {0}\r\n", Index + 1);
                Str.Append(ForDisplay(QRDecoder.ByteArrayToStr(DataByteArray[Index])));
            }
            return Str.ToString();
        }
        private static string ForDisplay
        (
        string Result
        )
        {
            int Index;
            for (Index = 0; Index < Result.Length && (Result[Index] >= ' ' && Result[Index] <= '~' || Result[Index] >= 160); Index++) ;
            if (Index == Result.Length) return Result;

            StringBuilder Display = new StringBuilder(Result.Substring(0, Index));
            for (; Index < Result.Length; Index++)
            {
                char OneChar = Result[Index];
                if (OneChar >= ' ' && OneChar <= '~' || OneChar >= 160)
                {
                    Display.Append(OneChar);
                    continue;
                }

                if (OneChar == '\r')
                {
                    Display.Append("\r\n");
                    if (Index + 1 < Result.Length && Result[Index + 1] == '\n') Index++;
                    continue;
                }

                if (OneChar == '\n')
                {
                    Display.Append("\r\n");
                    continue;
                }

                Display.Append('¿');
            }
            return Display.ToString();
        }

        [HttpPost]
        public JsonResult ProcessRequest()
        {
            HttpRequest request = System.Web.HttpContext.Current.Request;
            HttpPostedFile imgBinary = request.Files["image"];
            try
            {
                Stream iStream = imgBinary.InputStream;
                byte[] bytes = new byte[iStream.Length];
                iStream.Seek(0, SeekOrigin.Begin);
                iStream.Read(bytes, 0, bytes.Length);
                TypeConverter tc = TypeDescriptor.GetConverter(typeof(Bitmap));
                Bitmap bitmap = (Bitmap)tc.ConvertFrom(bytes);
                BarcodeReader reder = new BarcodeReader();

                ////////////////MessagingToolkit.QRCode.Codec.QRCodeDecoder decoder = new MessagingToolkit.QRCode.Codec.QRCodeDecoder();
                ////////////////string resulst = decoder.Decode(new QRCodeBitmapImage(bitmap));
                Result resulst = reder.Decode(bitmap);
                if (resulst != null)
                {
                    string s = resulst.Text;
                }
                return Json(resulst.Text.ToString(), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.Message.ToString(), JsonRequestBehavior.AllowGet);
            }

            //HttpRequest request = System.Web.HttpContext.Current.Request;
            //bool isSuccess = false;
            //Exception readBarcodeException = null;
            //TextResult[] results = null;
            //TimeSpan tsDecode = TimeSpan.Zero;
            //try
            //{
            //    // 1. Get Base64 Stream
            //    Request.InputStream.Position = 0;
            //    string jsonString;
            //    using (StreamReader streamReader = new StreamReader(request.InputStream))
            //    {
            //        jsonString = streamReader.ReadToEnd();
            //    }

            //    HttpPostedFile imgBinary = request.Files["image"];
            //    int barcodeFormat = int.Parse(request["barcodeFormat"]);
            //    if (imgBinary == null)
            //    {
            //        throw new Exception("Post data is null.");
            //    }

            //    // 2. load settings
            //    BarcodeReader barcodeReader = new BarcodeReader();
            //    barcodeReader.ProductKeys = System.Web.Configuration.WebConfigurationManager.AppSettings["barcodeReaderKey"];
            //    //Best coverage setting

EcomaintSite/EcomaintSite/Views/MyEcomain/Index - Copy.cshtml
@using Model.Data
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/_Layout.cshtml";
}
<style>
</style>
<div class="row">
    <div class="col-lg-12">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href='@Url.Action("index", "Dashboard")'>Dashboard</a></li>
            <li id="frmYeuCauCuaNSD" class="breadcrumb-item active" data-lang="lblmyEcomain">Tiếp nhận yêu cầu</li>
        </ol>
    </div>
</div>
<div ng-controller="MyEcomainController" ng-init="fn.Init()">
    <div class="row">
        <div class="col-lg-12">
            <div class="card-box">
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                        <div class="form-group">
                            <label data-lang="lblDiaDiem">Địa điểm</label>
                            @Html.DropDownList("cbbDiaDiem", ViewBag.NhaXuong as SelectList, new { data_live_search = "true", data_slide = "right", @class = "selectpicker form-control" })
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                        <div class="form-group">
                            <label data-lang="lblHeThong">Hệ thống</label>
                            @Html.DropDownList("cbbHeThong", ViewBag.HeThong as SelectList, new { data_live_search = "true", data_slide = "right", @class = "selectpicker form-control" })
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                        <div class="form-group">
                            <label data-lang="lblLoaiTS">Loại tài sản</label>
                            @Html.DropDownList("cbbLoaiMay", ViewBag.LoaiMay as SelectList, new { data_live_search = "true", data_slide = "right", @class = "selectpicker form-control" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="card-box">
                <ul id="myTabs" class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active"><a href="#tabWorkorder" aria-controls="tabWorkorder" role="tab" data-toggle="tab" data-lang="tabWorkorder">Phiếu bảo trì quá hạn</a></li>
                    <li role="presentation"><a href="#tabmonitoring" aria-controls="tabmonitoring" role="tab" data-toggle="tab" data-lang="tabMonitoring">Giám sát tình trạng đến hạng kiểm tra</a></li>
                </ul>
                <h6 style="margin: 20px 0 0 0;"></h6>
                <!-- Tab panes -->
                <div class="tab-content">
                    @*tab phieu bao tri*@
                    <div role="tabpanel" class="tab-pane active" id="tabWorkorder">
                        <div class="row">
                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                <div class="form-group">
                                    <label data-lang="lblTaisan">Tài sản</label>
                                    @Html.DropDownList("cbbMay", ViewBag.May as SelectList, new { data_live_search = "true", data_slide = "left", @class = "selectpicker form-control" })
                                </div>
                            </div>
                        </div>
                        @*table danh sách phiếu bảo trì đến và quá hạn kt*@
                        <div class="row">
                            <div class="col-lg-12">
                                <h5 class="card-title" data-lang="lblDSPhieuBaoTri">Danh sách phiếu bảo trì</h5>
                                <div class="form-group">
                                    <div class="table-responsive" style="overflow: auto">
                                        <table id="tbphieubaotri" class="table table-bordered table-condensed display">
                                            <thead>
                                                <tr>
                                                    <th>Phiếu bảo trì</th>
                                                    <th>Mã tài sản</th>
                                                    <th>Tên tài sản</th>
                                                    <th>Tên loại bảo trì</th>
                                                    <th>Ngày bắt đầu</th>
                                                    <th>Ngày kết thúc</th>
                                                    <th>Địa điểm</th>
                                                    <th>Tình trạng</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td colspan="8" data-lang="KhongCoDuLieu">Không có dữ liệu</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    @*tab giám sát tình trạng đến hạng*@
                    <div role="tabpanel" class="tab-pane" id="tabmonitoring">
                        <div class="row">
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                                <div class="form-group">
                                    <label data-lang="lblTaisan">Tài sản</label>
                                    @Html.DropDownList("cbbMayTS", ViewBag.May as SelectList, new { data_live_search = "true", data_slide = "left", @class = "selectpicker form-control" })
                                </div>
                            </div>

                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                                <div class="form-group">
                                    <label data-lang="lblLoaiCV">Loại công việc</label>
                                    @Html.DropDownList("cbbLoaiCV", ViewBag.LoaiCV as SelectList, new { data_live_search = "true", data_slide = "right", @class = "selectpicker form-control" })
                                </div>
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                                <div class="form-group">
                                    <label data-lang="lblTungay">Từ ngày</label>
                                    <input class="form-control" type="text" id="fromDate" data-type="datepicker" value="@DateTime.Now.AddMonths(-12).ToString("dd/MM/yyyy")" />
                                </div>
                            </div>

                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                                <div class="form-group">
                                    <label data-lang="lblDenngay">Đến ngày</label>
                                    <input class="form-control" type="text" id="toDate"  data-type="datepicker" value="@DateTime.Now.ToString("dd/MM/yyyy")" />
                                </div>
                            </div>
                        </div>

                        @*table giám sát tình trạng đến hạn kiểm tra*@
                        <div class="row">
                            <div class="col-lg-12">
                                @*<h5 class="card-title" data-lang="lblDSGiamSatTinhTrang">Danh sách giám sát tình trạng</h5>*@
                                <div class="form-group">
                                    <div class="table-responsive">
                                        <table id="tbgiamsattinhtrang" class="table table-bordered table-condensed display">
                                            <thead>
                                                <tr>
                                                    <th width="10%">Mã tài sản</th>
                                                    <th width="10%">Tên tài sản</th>
                                                    <th width="10%">Tên bộ phận</th>
                                                    <th width="10%">Thông số GSTT</th>
                                                    <th width="10%">Chu kỳ</th>
                                                    <th width="10%">Ngày KT cuối</th>
                                                    <th width="10%">Giá trị</th>
                                                    <th width="10%">Ngày KT kế</th>
                                                    <th width="10%">Cách thực hiện</th>
                                                    <th width="10%">Thời gian thực hiện</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td colspan="10" data-lang="KhongCoDuLieu">Không có dữ liệu</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="divButtonFloat" class="kc_fab_wrapper">
            </div>
        </div>
    </div>
</div>
<script>
   
    var urlPhieuBaoTri = '@Url.Action("GetPhieuBaoTri", "MyEcomain")';
    var urlGiamSatTinhTrang = '@Url.Action("GetGiamSatTinhTrang", "MyEcomain")';
        require(['MyEcomainController'])
</script>

EcomaintSite/EcomaintSite/Views/MyEcomain/Index.cshtml
@using Model.Data
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/_Layout.cshtml";
}
<div class="row">
    <div class="col-lg-12">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href='@Url.Action("index", "Dashboard")'>Dashboard</a></li>
            <li id="frmYeuCauCuaNSD" class="breadcrumb-item active" data-lang="lblmyEcomain">Tiếp nhận yêu cầu</li>
        </ol>
    </div>
</div>
<div ng-controller="MyEcomainController" ng-init="fn.Init()">
    <input type="file" id="fileToUpload" style="display: none;" />
    <div class="row">
        <div class="col-lg-12">
            <div class="card-box">
                <div class="row ">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                        <div class="form-group responsive">
                            <label data-lang="lblDiaDiem">Địa điểm</label>
                            @Html.DropDownList("cbbDiaDiem", ViewBag.NhaXuong as SelectList, new { name = "cbbDiaDiem", data_slide = "left", @class = "form-control select2-container--classic", @style = "width:100%" })
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                        <div class="form-group responsive">
                            <label data-lang="lblThietBi">Máy</label>
                            <div class="input-group">
                                @*@Html.DropDownList("cbbThietBi", ViewBag.NhaXuong as SelectList, new { name = "cbbThietBi", data_live_search = "true", data_slide = "left", @class = "form-control select2-container--classic", @style = "width:100%" })
                                    <a class="input-group-addon" id="ReadBtn" href="#"><span class="glyphicon glyphicon-barcode" aria-hidden="true"></span></a>*@
                                <input class="form-control" type="text" id="cbbThietBi" value="" />
                                <a class="input-group-addon" ng-click="fn.ShowEquipForm();" href="#"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="card-box">
                <ul id="myTabs" class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active"><a href="#tabWorkorder" aria-controls="tabWorkorder" role="tab" data-toggle="tab">Bảo trì</a></li>
                </ul>
                <h6 style="margin: 20px 0 0 0;"></h6>
                <!-- Tab panes -->
                <div class="tab-content">
                    @*tab phieu bao tri*@
                    <div role="tabpanel" class="tab-pane active" id="tabWorkorder">
                        <div class="row">
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                                <div class="radio">
                                    <label><input type="radio" name="optradio" value="1" checked>Giai đoạn</label>
                                </div>
                                <div class="radio">
                                    <label><input type="radio" name="optradio" value="0">Trong ngày</label>
                                </div>
                            </div>
                            <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
                                <div class="form-group">
                                    <label data-lang="lblTungay">Từ ngày</label>
                                    <input class="form-control" type="text" id="fromDate" data-type="datepicker" value="@DateTime.Now.AddMonths(-1).ToString("dd/MM/yyyy")" />
                                </div>
                            </div>
                            <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
                                <div class="form-group">
                                    <label data-lang="lblDenngay">Đến ngày</label>
                                    <input class="form-control" type="text" id="toDate" data-type="datepicker" value="@DateTime.Now.ToString("dd/MM/yyyy")" />
                                </div>
                            </div>
                        </div>
                        @*table danh sách phiếu bảo trì đến và quá hạn kt*@
                        <div class="row">
                            <div class="col-lg-12">
                                <h5 class="card-title" data-lang="lblDSPhieuBaoTri">Danh sách phiếu bảo trì</h5>
                                <div class="form-group">
                                    <div class="table-responsive" style="overflow: auto">
                                        <table id="tbmyecomain" class="table table-bordered table-condensed display">
                                            <thead>
                                                <tr>
                                                    <th>Mã tài sản</th>
                                                    <th>Tên tài sản</th>
                                                    <th>Bảo trì</th>
                                                    <th>Kiểm tra</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @*<tr>
                                                        <td colspan="8" data-lang="KhongCoDuLieu">Không có dữ liệu</td>
                                                    </tr>*@
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <div id="divButtonFloat" class="kc_fab_wrapper">
            </div>
        </div>
    </div>
</div>


@*model chon may*@
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" style="color: #15428B !important;" data-lang="lblChooseDevice">Chọn máy</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="table-responsive" style="overflow:auto">
                            <table id="tbEquip" style="width:100%" class="table table-bordered table-striped table-condensed ">
                                <thead>
                                    <tr>
                                        <th data-lang="DeviceID">DeviceID</th>
                                        <th data-lang="Description">Name</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @*@foreach (var item in Model)
                                    {
                                        <tr data-id="@item.ID">
                                            <td style="width: 150px">@item.ID</td>
                                            <td>@item.Name</td>
                                        </tr>
                                    }*@
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div id="divGhi" class="row ">
                    <div class="col-sm-3 col-md-2 col-xs-4 col-lg-3 pull-right">
                        <div class="form-group">
                            <input type="button" data-dismiss="modal" data-lang="btnHuy" style="color: #fff; width: 100%;" class="btn-flat flat" value="Hủy">
                        </div>
                    </div>
                    <div class="col-sm-3 col-md-2 col-xs-4 col-lg-3 pull-right">
                        <div class="form-group">
                            <input type="button" id="btnChooseEquip" style="color: #fff; width: 100%;" data-lang="btnChon" class="btn-flat flat" value="Chon">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="divButtonFloat" class="kc_fab_wrapper"></div>
</div>



<script>
    var urlPhieuBaoTri = '@Url.Action("GetPhieuBaoTri", "MyEcomain")';
    var urlGiamSatTinhTrang = '@Url.Action("GetGiamSatTinhTrang", "MyEcomain")';
    var urlMyecomain = '@Url.Action("GeMyecomain", "MyEcomain")';
    var urlFilterPBT = '@Url.Action("FilterData", "WorkOrder")';
    var urlDevices = '@Url.Action("getDevices", "UserRequest")';
    var urlReadbarcode = '@Url.Action("ProcessRequest", "MyEcomain")';
    var urlCheckTheParametersDue = '@Url.Action("CheckTheParametersDue", "Monitoring")';
    require(['MyEcomainController'])
</script>
@*<script src="~/js/controller/MobileBarcodeReader.js"></script>*@