EcomaintSite/EcomaintSite/Controllers/DashboardController.cs
using Microsoft.AspNet.Identity;
using Model.Interface;
using System;
using System.Linq;
using System.Web.Mvc;

namespace EcomaintSite.Controllers
{
    public class DashboardController : Controller
    {
        IUserRepository user;
        IChartRepository chart;
        public DashboardController(IUserRepository _user, IChartRepository _chart)
        {
            user = _user;
            chart = _chart;
        }
        [Authorize]
        public ActionResult Index()
        {
            var us = user.GetUserByID(User.Identity.GetUserName());
            ViewBag.TenNguoiDung = us.FullName;
            ViewBag.Username = User.Identity.GetUserName();
            ViewBag.PhongBan = user.GetPhongBan(Convert.ToInt32(us.DepartmentID));
            ViewBag.SoMay = chart.GetSoMay().ToString();
            return View();
        }

        public JsonResult GetDeviceInfo() =>
            Json(new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(chart.GetDeviceInfo(SessionVariable.TypeLanguage).ToList()).Replace("y\":\"", "y\":").Replace("\",\"color\":", ",\"color\":"), JsonRequestBehavior.AllowGet);
     
        public JsonResult GetDeviceStatus() =>
             Json(new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(chart.GetDeviceStatus(DateTime.Now, User.Identity.GetUserName(), SessionVariable.TypeLanguage).ToList()).Replace("y\":\"", "y\":").Replace("\",\"color\":", ",\"color\":"), JsonRequestBehavior.AllowGet);
     
        public JsonResult GetSituationWO() => 
            Json(new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(chart.GetSituationWO(SessionVariable.TypeLanguage).ToList()).Replace("\"[", "[").Replace("]\"", "]"), JsonRequestBehavior.AllowGet);
    
        public JsonResult GetSituationWOColumn() =>
            Json(new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(chart.GetSituationWOColumn(SessionVariable.TypeLanguage).ToList()).Replace("\"[", "[").Replace("]\"", "]"), JsonRequestBehavior.AllowGet);

    }
}

EcomaintSite/EcomaintSite/Controllers/PeriodicMaintenanceController.cs
using Model.Data;
using Model.Interface;

using Model.Repository;
using Model.UnitOfWork;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EcomaintSite.Controllers
{
    public class PeriodicMaintenanceController : Controller
    {
        IPeriodicMaintenanceRepository periodicMaintenanceRepository;
        IStaffRepository staffRepository;
        IMasterPlanUnitOfWork masterPlanUnitOfWork;
        IWorkOrderUnitOfWork workOrderUnitOfWork;

        public PeriodicMaintenanceController(IStaffRepository _staffRepository, IPeriodicMaintenanceRepository _periodicMaintenanceRepository, IMasterPlanUnitOfWork _masterPlanUnitOfWork, IWorkOrderUnitOfWork _workOrderUnitOfWork)
        {
            periodicMaintenanceRepository = _periodicMaintenanceRepository;           
            staffRepository = _staffRepository;
            masterPlanUnitOfWork = _masterPlanUnitOfWork;
            workOrderUnitOfWork = _workOrderUnitOfWork;
        }

        // GET:  PeriodicMaintenance
        [Authorize]
        public ActionResult Index()
        {
            ViewBag.cboCreatedBy = new SelectList(staffRepository.GetStaffRole(2, User.Identity.Name), "ID", "Name");
            ViewBag.cboMonitoredBy = new SelectList(staffRepository.GetStaffRole(3, User.Identity.Name), "ID", "Name");
            return View();
        }

        [Authorize]
        public JsonResult FilterData(string fromDate, string toDate, bool timeOut) =>
            Json(periodicMaintenanceRepository.GetPeriodicMaintenance(Convert.ToDateTime(fromDate, new CultureInfo("vi-vn")), Convert.ToDateTime(toDate, new CultureInfo("vi-vn")), "-1", "-1", "-1", "-1", "-1", User.Identity.Name, timeOut).Select(x => new
            {
                Choose = "",
                DeviceID = x.DeviceID,
                TypeOfMaintenanceName = x.TypeOfMaintenanceName,
                TypeOfMaintenanceID = x.TypeOfMaintenanceID,
                DeviceName = x.DeviceName,
                LastDate = x.LastDate.ToString("dd/MM/yyyy"),
                NextDate = x.NextDate.ToString("dd/MM/yyyy"),
                RuntimeCycle = x.RuntimeCycle,
                CurrentRunTime = x.CurrentRunTime,
                DeviceGroupName = x.DeviceGroupName,
                PriorityID = x.PriorityID
            }), JsonRequestBehavior.AllowGet);

        [Authorize]
        public JsonResult SavePlan(string data)
        {
            List<Model.Data.MasterPlan> lstPlans = Newtonsoft.Json.JsonConvert.DeserializeObject<List<Model.Data.MasterPlan>>(data);
            try
            {
                foreach (var item in lstPlans)
                {
                    item.Username = User.Identity.Name;
                    masterPlanUnitOfWork.MasterPlanRepository.Add(item);
                    var lstPreventiveMaintenanceOfWork = masterPlanUnitOfWork.PreventiveMaintenanceOfWorkRepository.GetPreventiveMaintenanceOfWork(item.DeviceID, item.TypeOfMaintenanceID.Value);
                    foreach (var preventiveMaintenanceOfWork in lstPreventiveMaintenanceOfWork)
                    {
                        Work work = masterPlanUnitOfWork.WorkRepository.GetWorkByID(preventiveMaintenanceOfWork.WorkID);
                        ComponentOfWork workComponent = masterPlanUnitOfWork.WorkComponentRepository.GetWorkComponentByID(preventiveMaintenanceOfWork.DeviceID, preventiveMaintenanceOfWork.ComponentID, preventiveMaintenanceOfWork.WorkID);
                        masterPlanUnitOfWork.MasterPlansOfWorkRepository.Add(new Model.Data.MasterPlansOfWork
                        {
                            DeviceID = preventiveMaintenanceOfWork.DeviceID,
                            PlanID = item.ID,
                            WorkID = preventiveMaintenanceOfWork.WorkID,
                            ComponentID = preventiveMaintenanceOfWork.ComponentID,
                            TimePlan = work.TimePlan.HasValue ? work.TimePlan : workComponent.TimePlan,
                            AmountOfPeople = work.AmountOfPeople,
                            InquiryHR = workComponent.InquiryHR,
                            Tool = workComponent.Tool
                        });

                        var lstPreventiveMaintenanceOfSparePart = masterPlanUnitOfWork.PreventiveMaintenanceOfSparePartRepository.GetPreventiveMaintenanceOfSparePart(item.DeviceID, item.TypeOfMaintenanceID.Value, preventiveMaintenanceOfWork.WorkID);
                        foreach (var preventiveMaintenanceOfSparePart in lstPreventiveMaintenanceOfSparePart)
                        {
                            masterPlanUnitOfWork.MasterPlansOfSparePartRepository.Add(new Model.Data.MasterPlansOfSparePart
                            {
                                DeviceID = preventiveMaintenanceOfSparePart.DeviceID,
                                PlanID = item.ID,
                                WorkID = preventiveMaintenanceOfSparePart.WorkID,
                                ComponentID = preventiveMaintenanceOfSparePart.ComponentID,
                                SparePartID = preventiveMaintenanceOfSparePart.SparePartID,
                                Amount = preventiveMaintenanceOfSparePart.Amount
                            });
                        }
                    }
                    masterPlanUnitOfWork.Save();
                }
                return Json("success");
            }
            catch (Exception ex)
            {
                return Json("failed: " + ex.InnerException.Message);
            }
        }

        [Authorize]
        public JsonResult SaveWO(string data)
        {
            List<Model.Data.WorkOrder> lstWO = Newtonsoft.Json.JsonConvert.DeserializeObject<List<Model.Data.WorkOrder>>(data);
            try
            {
                List<string> lstWONumber = new List<string>();
                List<WorkOrderOfWork> lstWork = new List<WorkOrderOfWork>();
                List<WorkOrderOfWorkIncludeSparePart> lstSparePart = new List<WorkOrderOfWorkIncludeSparePart>();
                List<WorkOrderOfWorkIncludeDetailSparePart> lstDetailSparePart = new List<WorkOrderOfWorkIncludeDetailSparePart>();
                List<WorkOrderDetailsByTheState> lstWOStatus = new List<WorkOrderDetailsByTheState>();
                List<ComponentOfSparePart> lstSparePartComponent = new List<ComponentOfSparePart>();

                string workOrderID = workOrderUnitOfWork.WorkOrderRepository.GenerateWorkOrderID(User.Identity.Name, DateTime.Now.Year, DateTime.Now.Month);
                foreach (var item in lstWO)
                {
                    item.ID = workOrderID;
                    item.DateCreated = DateTime.Now;
                    item.TimeCreated = DateTime.Now;
                    item.UserCreated = User.Identity.Name;
                    item.PriorityID = item.PriorityID == null ? workOrderUnitOfWork.PriorityRepository.ListAll().Max(x => x.ID) : item.PriorityID;
                    item.TheStatusOfWorkOrderID = workOrderUnitOfWork.TheStatusDetailsOfWorkOrderRepository.GetTheStatusDetailsOfWorkOrderByID(item.TheStatusOfWorkOrderID ?? 1).TheStatusOfWorkOrderID;
                    item.LastDateModified = item.StartDatePlan;
                    item.OriginalStartDate = item.StartDatePlan;
                    if (workOrderUnitOfWork.GeneralRepository.GetGeneralInfo().MDEFAULT.HasValue && workOrderUnitOfWork.GeneralRepository.GetGeneralInfo().MDEFAULT == 1)
                        item.WorkOrderNo = workOrderID;
                    lstWOStatus.Add(new WorkOrderDetailsByTheState
                    {
                        WorkOrderID = workOrderID,
                        TheStatusOfWorkOrderID = item.TheStatusOfWorkOrderID,
                        ID = 1,
                        Username = item.UserCreated,
                        DateCreated = item.DateCreated
                    });
                    var lstPreventiveMaintenanceOfWork = workOrderUnitOfWork.PreventiveMaintenanceOfWorkRepository.GetPreventiveMaintenanceOfWork(item.DeviceID, item.TypeOfMaintenanceID.Value);
                    foreach (var preventiveMaintenanceOfWork in lstPreventiveMaintenanceOfWork)
                    {
                        Work work = workOrderUnitOfWork.WorkRepository.GetWorkByID(preventiveMaintenanceOfWork.WorkID);
                        ComponentOfWork workComponent = workOrderUnitOfWork.WorkComponentRepository.GetWorkComponentByID(preventiveMaintenanceOfWork.DeviceID, preventiveMaintenanceOfWork.ComponentID, preventiveMaintenanceOfWork.WorkID);
                        lstWork.Add(new Model.Data.WorkOrderOfWork
                        {
                            WorkOrderID = workOrderID,
                            WorkID = preventiveMaintenanceOfWork.WorkID,
                            ComponentID = preventiveMaintenanceOfWork.ComponentID,
                            Tool = workComponent.Tool,
                            InquiryHR = workComponent.InquiryHR,
                            HourPlan = workComponent.TimePlan,
                            ActualTime  = workComponent.TimePlan,
                            Action = workComponent.Action,
                            QualityCheck = workComponent.QualityCheck,
                            AmountOfPeople = work.AmountOfPeople,
                            Path = workComponent.Path,
                            WorkStartDate = item.StartDatePlan,
                            WorkEndDate = item.StartDatePlan
                        });

                        if (workOrderUnitOfWork.GeneralRepository.GetGeneralInfo().THEM_CV_PT.HasValue && workOrderUnitOfWork.GeneralRepository.GetGeneralInfo().THEM_CV_PT.Value != 0) continue;

EcomaintSite/EcomaintSite/Views/PeriodicMaintenance/Index.cshtml
@using Model.Data
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/_Layout.cshtml";
}
<style>
    #tbPeriodicMaintenance > tbody > tr > td {
        word-break: break-all;
    }

    div.FixedHeader_Cloned th,
    div.FixedHeader_Cloned td {
        background-color: white !important;
    }
</style>
<div ng-controller="PeriodicMaintenanceController" ng-init="fn.Init()">
    <div class="row">
        <div class="col-lg-12">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href='@Url.Action("Index", "Dashboard")'>Dashboard</a></li>
                <li class="breadcrumb-item"><a href='@Url.Action("Index", "MasterPlans")' data-lang="lblKHTT">Kế hoạch tổng thể</a></li>
                <li class="breadcrumb-item active" data-lang="lblBaoTriDK">Bảo trì định kỳ</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="card-box">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                        <div class="form-group">
                            <label data-lang="lblTuNgay">Từ ngày</label>
                            <input class="form-control" type="text" id="fromDate" data-loading="true" data-type="datepicker" value="@DateTime.Now.AddMonths(-1).ToString("dd/MM/yyyy")" />
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                        <div class="form-group">
                            <label data-lang="lblDenNgay">Đến ngày</label>
                            <input class="form-control" type="text" id="toDate" data-loading="true" data-type="datepicker" value="@DateTime.Now.ToString("dd/MM/yyyy")" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                        <div class="form-group">
                            <label data-lang="lblNguoiLap">Người lập</label>
                            @Html.DropDownList("cboCreatedBy", ViewBag.cboCreatedBy as SelectList, new { data_live_search = "true", data_slide = "right", @class = " selectpicker form-control" })
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                        <div class="form-group">
                            <label data-lang="lblNguoiGiamSat">Người giám sát</label>
                            @Html.DropDownList("cboMonitoredBy", ViewBag.cboMonitoredBy as SelectList, new { data_live_search = "true", data_slide = "right", @class = " selectpicker form-control" })
                        </div>
                    </div>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="form-group" data-toggle="buttons">
                            <label class="btn">
                                <input class="form-control" type="checkbox" id="ckTimeOut" />
                                <i class="fa fa-square-o"></i><i class="fa fa-check-square-o"></i>
                                <span data-lang="lblDugio"> Đủ giờ</span>
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="card-box">
                <div id="divButtonDefault" class="toolbar-action">
                    <button ng-click="fn.CreateWO();" type="button" data-lang="btnCreateWO" id="btnCreateWO" class="btn btn-default pull-right">
                        <i class="fa fa-recycle" aria-hidden="true"></i>
                    </button>
                    <button ng-click="fn.CreatePlans();" type="button" data-lang="btnKHTT" id="btnKHTT" class="btn btn-default pull-right">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    </button>
                </div>
                <h5 class="card-title" data-lang="lblBaoTriDK">Bảo trì định kỳ cần thực hiện</h5>
                <div class="form-group">
                    <div class="table-responsive" style="overflow: auto">
                        <table id="tbPeriodicMaintenance" class="table table-bordered table-condensed ">
                            <thead>
                                <tr>
                                    <th data-lang="Choose">Chọn</th>
                                    <th data-lang="DeviceID">Mã máy</th>
                                    <th data-lang="Name">Tên máy</th>
                                    <th data-lang="TEN_LOAI_BT">Loại BT</th>
                                    <th data-lang="NGAY_CUOI">Ngày cuối</th>
                                    <th data-lang="NGAY_BTKT">Ngày đến hạn</th>
                                    <th data-lang="TGCM">Chu kỳ RuntimeCycle</th>
                                    <th data-lang="TGCM_HIEN_TAI">RuntimeCycle hiện tại</th>
                                    <th data-lang="TEN_NHOM_MAY">Nhóm máy</th>
                                    <th data-lang="Priority">Mức ưu tiên</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="divButtonFloat" class="kc_fab_wrapper"></div>
    <script>
        var urlFilter = '@Url.Action("FilterData", "PeriodicMaintenance")';
        var urlSaveMasterPlan = '@Url.Action("SavePlan", "PeriodicMaintenance")';
        var urlSaveWO = '@Url.Action("SaveWO", "PeriodicMaintenance")';
        require(['PeriodicMaintenanceController'])
    </script>
</div>