EcomaintSite/EcomaintSite/Controllers/DashboardController.cs
using Microsoft.AspNet.Identity;
using Model.Interface;
using System;
using System.Linq;
using System.Web.Mvc;

namespace EcomaintSite.Controllers
{
    public class DashboardController : Controller
    {
        IUserRepository user;
        IChartRepository chart;
        public DashboardController(IUserRepository _user, IChartRepository _chart)
        {
            user = _user;
            chart = _chart;
        }
        [Authorize]
        public ActionResult Index()
        {
            var us = user.GetUserByID(User.Identity.GetUserName());
            ViewBag.TenNguoiDung = us.FullName;
            ViewBag.Username = User.Identity.GetUserName();
            ViewBag.PhongBan = user.GetPhongBan(Convert.ToInt32(us.DepartmentID));
            ViewBag.SoMay = chart.GetSoMay().ToString();
            return View();
        }

        public JsonResult GetDeviceInfo() =>
            Json(new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(chart.GetDeviceInfo(SessionVariable.TypeLanguage).ToList()).Replace("y\":\"", "y\":").Replace("\",\"color\":", ",\"color\":"), JsonRequestBehavior.AllowGet);
     
        public JsonResult GetDeviceStatus() =>
             Json(new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(chart.GetDeviceStatus(DateTime.Now, User.Identity.GetUserName(), SessionVariable.TypeLanguage).ToList()).Replace("y\":\"", "y\":").Replace("\",\"color\":", ",\"color\":"), JsonRequestBehavior.AllowGet);
     
        public JsonResult GetSituationWO() => 
            Json(new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(chart.GetSituationWO(SessionVariable.TypeLanguage).ToList()).Replace("\"[", "[").Replace("]\"", "]"), JsonRequestBehavior.AllowGet);
    
        public JsonResult GetSituationWOColumn() =>
            Json(new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(chart.GetSituationWOColumn(SessionVariable.TypeLanguage).ToList()).Replace("\"[", "[").Replace("]\"", "]"), JsonRequestBehavior.AllowGet);

    }
}

EcomaintSite/EcomaintSite/Controllers/WorkOrderController.cs
using Model.Combobox;
using Model.Data;
using Model.Interface;
using Model.Repository;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;

namespace EcomaintSite.Controllers
{
    public class WorkOrderController : Controller
    {
        IStaffRepository staffRepository;
        IDeviceRepository deviceRepository;
        IPriorityRepository priorityRepository;
        IGeneralRepository generalRepository;
        IWorkOrderRepository workOrderRepository;
        ITypeOfMaintenanceRepository typeOfMaintenanceRepository;
        IComponentRepository componentRepository;
        IWorkOrderOfSparePartRepository workOrderOfSparePartRepository;
        IWorkComponentRepository workComponentRepository;
        IWorkRepository workRepository;
        IWorkOrderOfWorkRepository workOrderOfWorkRepository;
        ISparePartRepository sparePartRepository;
        IWorkOrderUnitOfWork workOrderUnitOfWork;

        private ICombobox _Combobox;
        private ICombobox Combobox()
        {
            return _Combobox ?? (_Combobox = new Combobox());
        }

        public WorkOrderController(IStaffRepository _staffRepository, IDeviceRepository _deviceRepository, IPriorityRepository _priorityRepository, IGeneralRepository _generalRepository, IWorkOrderRepository _workOrderRepository, ITypeOfMaintenanceRepository _typeOfMaintenanceRepository, IComponentRepository _componentRepository, IWorkOrderOfSparePartRepository _workOrderOfSparePartRepository, IWorkComponentRepository _workComponentRepository, IWorkRepository _workRepository, IWorkOrderOfWorkRepository _workOrderOfWorkRepository, ISparePartRepository _sparePartRepository, IWorkOrderUnitOfWork _workOrderUnitOfWork)
        {
            staffRepository = _staffRepository;
            deviceRepository = _deviceRepository;
            priorityRepository = _priorityRepository;
            generalRepository = _generalRepository;
            workOrderRepository = _workOrderRepository;
            typeOfMaintenanceRepository = _typeOfMaintenanceRepository;
            componentRepository = _componentRepository;
            workOrderOfSparePartRepository = _workOrderOfSparePartRepository;
            workComponentRepository = _workComponentRepository;
            workRepository = _workRepository;
            workOrderOfWorkRepository = _workOrderOfWorkRepository;
            sparePartRepository = _sparePartRepository;
            workOrderUnitOfWork = _workOrderUnitOfWork;
        }
        
        [Authorize]
        public ActionResult Index()
        {
            ViewBag.link = 0;
            ViewBag.cboCreatedBy = new SelectList(staffRepository.GetStaffRole(2, User.Identity.Name).Select(x =>
            new
            {
                ID = x.ID,
                Name = x.Name
            }).ToList(), "ID", "Name");

            ViewBag.cboDevice = new SelectList(deviceRepository.ListAll().Select(x =>
            new Model.Data.DeviceObjForDropdown
            {
                ID = x.ID,
                Name = x.ID + " - " + (SessionVariable.TypeLanguage == 0 ? x.Name : x.NameOfEng)
            }).ToList(), "ID", "Name");

            ViewBag.cboPriority = new SelectList(priorityRepository.ListAll().Select(x =>
            new
            {
                ID = x.ID,
                Name = (SessionVariable.TypeLanguage == 0 ? x.Name : x.NameOfEng)
            }), "ID", "Name");
            ViewBag.IsAuto = generalRepository.GetGeneralInfo().IsAuto;
            ViewBag.NhaXuong = Combobox().GetCbbDiaDiem(User.Identity.Name, SessionVariable.TypeLanguage,1);
            return View();
        }

        [Authorize]
        public ActionResult Show(string msnx, string msmay,string todate,string fromdate)
        {
            ViewBag.link = 1;
            ViewBag.nx = msnx;
            ViewBag.may = msmay;
            ViewBag.tngay = Convert.ToDateTime(todate, new CultureInfo("vi-vn")).ToString("dd/MM/yyyy");
            ViewBag.dngay = Convert.ToDateTime(fromdate, new CultureInfo("vi-vn")).ToString("dd/MM/yyyy");
            ViewBag.cboCreatedBy = new SelectList(staffRepository.GetStaffRole(2, User.Identity.Name).Select(x =>
                        new
                        {
                            ID = x.ID,
                            Name = x.Name
                        }).ToList(), "ID", "Name");

            ViewBag.cboDevice = new SelectList(deviceRepository.ListAll().Select(x =>
            new Model.Data.DeviceObjForDropdown
            {
                ID = x.ID,
                Name = x.ID + " - " + (SessionVariable.TypeLanguage == 0 ? x.Name : x.NameOfEng)
            }).ToList(), "ID", "Name");

            ViewBag.cboPriority = new SelectList(priorityRepository.ListAll().Select(x =>
            new
            {
                ID = x.ID,
                Name = (SessionVariable.TypeLanguage == 0 ? x.Name : x.NameOfEng)
            }), "ID", "Name");
            ViewBag.IsAuto = generalRepository.GetGeneralInfo().IsAuto;
            ViewBag.NhaXuong = Combobox().GetCbbDiaDiem(User.Identity.Name, SessionVariable.TypeLanguage, 1);
            return View("~/Views/WorkOrder/Index.cshtml", deviceRepository.ListAll().Select(x => new DeviceObjForDropdown
            {
                ID = x.ID,
                Name = x.Name
            }).ToList());
        }

        [Authorize]
        public ActionResult GetWorkOrderNumber() =>
            Json(workOrderRepository.GenerateWorkOrderID(User.Identity.Name, DateTime.Now.Year, DateTime.Now.Month), JsonRequestBehavior.AllowGet);

        [Authorize]
        public ActionResult GetTypeOfMaintenanceByDevice(string deviceID) =>
             Json(typeOfMaintenanceRepository.GetTypeOfMaintenanceByDevice(deviceID).Select(x => new
             {
                 TypeOfMaintenanceID = x.ID,
                 TypeOfMaintenanceName = x.Name
             }), JsonRequestBehavior.AllowGet);
        
        [Authorize]
        public JsonResult GetComponentByDevice(string deviceID) =>
            Json(componentRepository.GetComponentByDevice(deviceID, SessionVariable.TypeLanguage).Select(x => new
            {
                id = x.ID,
                text = x.Name,
                parentid = x.RootID
            }), JsonRequestBehavior.AllowGet);


        [Authorize]
        public JsonResult GetWorkByComponent(string deviceID, string componentID) =>
             Json(workComponentRepository.GetWorkByComponent(deviceID, componentID, SessionVariable.TypeLanguage), JsonRequestBehavior.AllowGet);

        [Authorize]
        public JsonResult GetSparePart() => Json(sparePartRepository.GetSparePart(User.Identity.Name).Select(x =>
            new
            {
                SparePartID = x.ID,
                SparePartName = SessionVariable.TypeLanguage == 0 ? x.Name : x.NameOfEng,
                Specification = x.Specification,
                UnitOfCalculationID = x.UnitOfCalculationID
            }).ToList(), JsonRequestBehavior.AllowGet);
        [Authorize]
        public JsonResult FilterData(string  msnx,string msmay,string fromDate, string toDate, int type)
        {
            try
            {
                if (string.IsNullOrEmpty(msmay)) msmay = "-1";
                var model = workOrderRepository.GetWorkOrder(msnx,msmay,User.Identity.Name, Convert.ToDateTime(fromDate, new System.Globalization.CultureInfo("vi-vn")), Convert.ToDateTime(toDate, new System.Globalization.CultureInfo("vi-vn")), type, SessionVariable.TypeLanguage).Select(x => new
                {
                    Document = x.Document,
                    ID = x.WorkOrderID,
                    DeviceID = x.DeviceID,
                    DeviceName = x.DeviceName,
                    TheStatusOfWorkOrderID = x.TheStatusOfWorkOrderID,
                    PriorityName = x.PriorityName,
                    TheStatusDetailsOfWorkOrderName = x.TheStatusDetailsOfWorkOrderName,
                    TheStatusOfWorkOrderName = x.TheStatusOfWorkOrderName,
                    Reason = x.Reason,
                    DateCreated = x.DateCreated.HasValue ? x.DateCreated.Value.ToString("dd/MM/yyyy") : "",
                    WorkSiteName = x.WorkSiteName,
                    TypeOfMaintenanceID = x.TypeOfMaintenanceID,
                    TimeCreated = x.TimeCreated.HasValue ? x.TimeCreated.Value.ToString("HH:mm") : "",
                    TypeOfMaintenanceName = x.TypeOfMaintenanceName,
                    CreatedBy = x.CreatedBy,
                    UserCreated = x.UserCreated,
                    StaffName = x.StaffName,
                    MonitoredBy = x.MonitoredBy,
                    StartDatePlan = x.StartDatePlan.HasValue ? x.StartDatePlan.Value.ToString("dd/MM/yyyy") : "",
                    EndDatePlan = x.EndDatePlan.HasValue ? x.EndDatePlan.Value.ToString("dd/MM/yyyy") : "",
                    BreakdownStartTime = x.BreakdownStartTime.HasValue ? x.BreakdownStartTime.Value.ToString("HH:mm") : "",
                    BreakdownStartDate = x.BreakdownStartDate.HasValue ? x.BreakdownStartDate.Value.ToString("dd/MM/yyyy") : "",
                    BreakdownEndTime = x.BreakdownEndTime.HasValue ? x.BreakdownEndTime.Value.ToString("HH:mm") : "",
                    BreakdownEndDate = x.BreakdownEndDate.HasValue ? x.BreakdownEndDate.Value.ToString("dd/MM/yyyy") : "",
                    IssuedID = x.IssuedID,
                    LastDateModified = x.LastDateModified.HasValue ? x.LastDateModified.Value.ToString("dd/MM/yyyy") : ""
                });
                return Json(model, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json("error", JsonRequestBehavior.AllowGet);
            }
        }

        [Authorize]
        public JsonResult GetWorkOrderDetail(string workOrderID)
        {
            var model = workOrderOfSparePartRepository.GetWorkOrderOfSparePart(workOrderID).Select(x => new

EcomaintSite/EcomaintSite/Controllers/WorkWorkerController.cs
//using Dynamsoft.Barcode;
using Microsoft.AspNet.Identity;
using Model.Combobox;
using Model.Interface;
using Model.Interface.IRepository;
using Model.Repository.Repository;
//using Newtonsoft.Json;
//using Newtonsoft.Json.Linq;
using System;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//using ZXing;
using System.Text;
using QRCodeDecoderLibrary;
using ZXing;
using System.Drawing;
using System.ComponentModel;
using Model.Repository;
//using IronBarCode;

namespace EcomaintSite.Controllers
{
    public class WorkWorkerController : Controller
    {
        IDeviceRepository deviceRepository;
        private ICombobox _Combobox;
        private IMyEcomainRepository _MyEcomainRepository;
        private ICombobox Combobox()
        {
            return _Combobox ?? (_Combobox = new Combobox());
        }
        private IMyEcomainRepository WorkWorker()
        {
            return _MyEcomainRepository ?? (_MyEcomainRepository = new MyEcomainRepository());
        }

        public WorkWorkerController(IDeviceRepository _deviceRepository)
        {
            deviceRepository = _deviceRepository;
        }

        // GET: MyEcomain
        [Authorize]
        public ActionResult Index()
        {
            ViewBag.NhaXuong = Combobox().GetCbbDiaDiem(User.Identity.Name, SessionVariable.TypeLanguage, 1);
            ViewBag.cboDevice = new SelectList(deviceRepository.ListAll().Select(x =>
            new Model.Data.DeviceObjForDropdown
            {
                ID = x.ID,
                Name = x.ID + " - " + (SessionVariable.TypeLanguage == 0 ? x.Name : x.NameOfEng)
            }).ToList(), "ID", "Name");
            return View();
        }
    }
}

EcomaintSite/EcomaintSite/Views/WorkWorker/Index.cshtml
@using Model.Data
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/_Layout.cshtml";
}
<div class="row">
    <div class="col-lg-12">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href='@Url.Action("index", "Dashboard")'>Dashboard</a></li>
            <li id="frmYeuCauCuaNSD" class="breadcrumb-item active" data-lang="lblWorkWorker">Tiếp nhận yêu cầu</li>
        </ol>
    </div>
</div>
<div ng-controller="WorkWorkerController" ng-init="fn.Init()">

    <div class="card-box">
        <div class="row">
            <div class="col-lg-12">
                <div class="row">
                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                        <div class="form-group">
                            <label data-lang="lblTuNgay">Từ ngày</label>
                            <input class="form-control" type="text" id="fromDate" data-loading="true" data-type="datepicker" value="@DateTime.Now.AddMonths(-1).ToString("dd/MM/yyyy")" />
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                        <div class="form-group">
                            <label data-lang="lblDenNgay">Đến ngày</label>
                            <input class="form-control" type="text" id="toDate" data-loading="true" data-type="datepicker" value="@DateTime.Now.ToString("dd/MM/yyyy")" />
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                        <div class="form-group responsive">
                            <label data-lang="lblDiaDiem">Địa điểm</label>
                            @Html.DropDownList("cbbDiaDiem", ViewBag.NhaXuong as SelectList, new { name = "cbbDiaDiem", data_live_search = "true", data_slide = "left", @class = "form-control select-one select2", @style = "width:100%" })
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                        <div class="form-group responsive">
                            <label data-lang="lblThietBi">Máy</label>
                            @Html.DropDownList("cbbThietBi", ViewBag.cboDevice as SelectList, new { name = "cbbThietBi", data_live_search = "true", data_slide = "left", @class = "form-control select-one select2", @style = "width:100%" })
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12 col-lg-6">
                <h5 class="card-title" data-lang="lblPBT">Danh sách kế hoạch</h5>
                <div class="form-group">
                    <div class="table-responsive" style="overflow: auto">
                        <table id="tbWO" class="table table-bordered table-condensed ">
                            <thead>
                                <tr>
                                    <th data-lang="ID"></th>
                                    <th data-lang="DeviceID"></th>
                                    <th data-lang="DeviceName"></th>
                                    <th data-lang="TypeOfMaintenanceName"></th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>


            <div class="col-xs-12 col-lg-6">
                <div id="divButtonDefault" class="toolbar-action">
                    <button data-ng-click="fn.Removebp()" type="button" data-lang="btnXoabp" id="btnXoabp" class="btn btn-default pull-right">
                        <i class="fa fa-trash" aria-hidden="true"></i>
                    </button>
                    <button onclick="thembophan()" type="button" data-lang="btnThembp" id="btnThembp" class="btn btn-default pull-right">
                        <i class="fa fa-plus-circle" aria-hidden="true"></i>
                    </button>
                </div>

                <h5 class="card-title" data-lang="lblPBT">Nhân sự không theo công việc</h5>
                <div class="form-group">
                        <div class="container-fluid"style="height:42px; padding-top:5px;text-align :center">
                            <div class="radio-inline">
                                <label><input type="radio" name="optradio" value="1" checked>Kế hoạch</label>
                            </div>
                            <div class="radio-inline">
                                <label><input type="radio" name="optradio" value="0">Thực tế</label>
                            </div>
                    </div>

                    <div class="table-responsive" style="overflow: auto;">
                        <table id="tbPBTNS" class="table table-bordered table-condensed ">
                            <thead>
                                <tr>
                                    <th data-lang="CONG_NHAN">Nhân viên</th>
                                    <th data-lang="NGAY">Ngày</th>
                                    <th data-lang="TU_GIO">Từ giờ</th>
                                    <th data-lang="DEN_NGAY">Đến ngày</th>
                                    <th data-lang="DEN_GIO">Đến giờ</th>
                                    <th data-lang="SO_GIO">Số phút</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td colspan="5" data-lang="KhongCoDuLieu">Không có dữ liệu</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<script>
    var urlFilter = '@Url.Action("FilterData", "WorkOrder")';
    var urlDevices = '@Url.Action("getDevices", "UserRequest")';
    var urlDevices = '@Url.Action("getDevices", "WorkWorker                                                          " +
                     "    " +
                     "")';

    require(['WorkWorkerController'])
</script>